spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:8081/test?authSource=admin
      password: "root"
      username: "root"
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
  batch:
    job:
      enabled: false