spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    schema: schema.sql
    data: data.sql



#  SELECT books.id, book_name, author_name, genre_name FROM BOOKS inner join authors on books.author_id = authors.id inner join genres on books.genre_id = genres.id